"""Property 1: 이미지 생성 폴백 체인 정확성 (Validates: Requirements 1.1).

For any sequence of model success/failure outcomes across the image generation
chain (IMAGE_MODELS — Stability Ultra → SD3.5 → Stable Image Core → Nova Canvas
→ Titan Image v2), `_tool_generate_image` MUST:

  1. try every declared model in chain order — never skip a model;
  2. return the *first successful* model's identifier in the response;
  3. when every model fails, return ``error == "model-unavailable"`` with a
     ``detail`` string capped at 200 chars and sourced from the LAST model's
     failure (i.e. preserving deterministic chain order);
  4. include the three Req 1.1 anchor models (sd3-5-large, stable-image-core,
     titan-image-generator-v2) in the chain in that relative order.

The property is exercised by patching ``gw.invoke_model`` with a per-call
outcome list (``ok`` / ``err`` / ``exc``) generated by hypothesis and
inspecting the recorded call list together with the parsed JSON response.

Run:
  ai_engine/.venv/bin/python scripts/test_image_generation_fallback_chain_property.py
"""
from __future__ import annotations

import asyncio
import base64
import json
import os
import random as _random
import sys
import tempfile
from io import BytesIO
from unittest.mock import patch, MagicMock

# Make the ai_engine package importable from the repo root.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from hypothesis import given, settings, strategies as st  # noqa: E402
from PIL import Image  # noqa: E402

import ai_engine.server as server  # noqa: E402
from ai_engine.server import (  # noqa: E402
    IMAGE_MODELS,
    _tool_generate_image,
)


# ---------- fixtures: high-entropy PNG payload (>5KB after b64 decode) ----------

def _make_high_entropy_png(seed: int = 42, side: int = 256) -> bytes:
    rnd = _random.Random(seed)
    raw = bytes(rnd.randrange(256) for _ in range(side * side * 3))
    img = Image.frombytes("RGB", (side, side), raw)
    buf = BytesIO()
    # Low compression ensures the PNG comfortably exceeds the 5_000-byte
    # guard inside _save_and_score().
    img.save(buf, format="PNG", compress_level=1)
    return buf.getvalue()


_PNG_BYTES = _make_high_entropy_png()
_PNG_B64 = base64.b64encode(_PNG_BYTES).decode("ascii")
assert len(_PNG_BYTES) > 10_000, (
    f"fixture PNG must exceed _save_and_score min size (got {len(_PNG_BYTES)})"
)


# ---------- chain simulator ----------

def _strip_region_prefix(model_id: str) -> str:
    """Strip us./eu./global. prefix attached by _resolve_callable_model_id."""
    for p in ("us.", "eu.", "global."):
        if model_id.startswith(p):
            return model_id[len(p):]
    return model_id


class _ChainSimulator:
    """Records every invoke_model call and replays per-model outcomes.

    The impl calls models in parallel via asyncio.gather, so the recorded
    call order may interleave; what matters is the SET of called models and
    the per-model outcome we replay (keyed by model_id, not call index).
    """

    def __init__(self, outcomes_by_model: dict[str, str]):
        self.outcomes = outcomes_by_model
        self.calls: list[str] = []

    async def invoke_model(self, model_id, body, timeout=60):
        stripped = _strip_region_prefix(model_id)
        self.calls.append(stripped)
        outcome = self.outcomes.get(stripped, "err")
        if outcome == "ok":
            return {"images": [_PNG_B64]}
        if outcome == "err":
            return {"error": f"simulated error for {stripped}"}
        # outcome == "exc"
        raise RuntimeError(f"simulated exception for {stripped}")


def _run_chain(outcomes_by_model: dict[str, str], chain: list[str]):
    """Execute _tool_generate_image with a fully-patched gateway.

    Returns ``(parsed_json, called_models)``.

    * Forces ``AE_IMAGE_PARALLEL_N == len(chain)`` so every chain model is
      attempted, ensuring the property covers the entire chain.
    * Disables the quality-threshold auto-retry (``AE_IMAGE_QUALITY_THRESHOLD=0``)
      to keep behaviour deterministic for the property assertion.
    * Resets the image-gen circuit breaker so prior runs cannot short-circuit
      this invocation.
    """
    sim = _ChainSimulator(outcomes_by_model)
    mock_gw = MagicMock()
    mock_gw.invoke_model = sim.invoke_model

    # Reset circuit breaker.
    server._IMAGE_GEN_CIRCUIT["disabled_at"] = 0

    prev_parallel = os.environ.get("AE_IMAGE_PARALLEL_N")
    prev_threshold = os.environ.get("AE_IMAGE_QUALITY_THRESHOLD")
    os.environ["AE_IMAGE_PARALLEL_N"] = str(len(chain))
    os.environ["AE_IMAGE_QUALITY_THRESHOLD"] = "0"

    try:
        with tempfile.TemporaryDirectory() as tmp:
            # The prompt below contains none of the keyword sets recognised by
            # _select_image_models, so it falls through to the default IMAGE_MODELS
            # chain — the one Req 1.1 governs.
            tool_input = {
                "prompt": "neutral test scene xyz",
                "size": "1024x1024",
            }
            with patch.object(server, "_get_gw", return_value=mock_gw), \
                 patch.object(server, "_resolve_callable_model_id",
                              side_effect=lambda mid, *a, **k: mid):
                raw = asyncio.run(_tool_generate_image(tool_input, project_path=tmp))
            parsed = json.loads(raw)
            # Snapshot detected output files so we can sanity-check `path` exists
            # before the tempdir is torn down.
            gen_dir = os.path.join(tmp, ".generated")
            if "path" in parsed and parsed["path"].startswith(".generated/"):
                abs_out = os.path.join(tmp, parsed["path"])
                parsed["_abs_exists"] = os.path.isfile(abs_out)
            else:
                parsed["_abs_exists"] = False
    finally:
        # Restore env to avoid leaking between hypothesis examples.
        if prev_parallel is None:
            os.environ.pop("AE_IMAGE_PARALLEL_N", None)
        else:
            os.environ["AE_IMAGE_PARALLEL_N"] = prev_parallel
        if prev_threshold is None:
            os.environ.pop("AE_IMAGE_QUALITY_THRESHOLD", None)
        else:
            os.environ["AE_IMAGE_QUALITY_THRESHOLD"] = prev_threshold
        server._IMAGE_GEN_CIRCUIT["disabled_at"] = 0

    return parsed, sim.calls


def _first_success_in_chain(outcomes_by_model: dict[str, str], chain: list[str]):
    for m in chain:
        if outcomes_by_model.get(m) == "ok":
            return m
    return None


# ---------- structural invariants of the chain (Req 1.1 anchors) ----------

def test_chain_anchors():
    """Req 1.1 names sd3-5-large → stable-image-core → titan-image-generator-v2.

    The implementation chain may include additional models, but the relative
    order of these three Req 1.1 anchor models must be preserved.
    """
    sd35 = "stability.sd3-5-large-v1:0"
    core = "stability.stable-image-core-v1:1"
    titan = "amazon.titan-image-generator-v2:0"
    for m in (sd35, core, titan):
        assert m in IMAGE_MODELS, f"Req 1.1 anchor missing from chain: {m!r} (chain={IMAGE_MODELS})"
    assert IMAGE_MODELS.index(sd35) < IMAGE_MODELS.index(core) < IMAGE_MODELS.index(titan), (
        f"Req 1.1 anchor ordering violated: {IMAGE_MODELS}"
    )


# ---------- Property 1: fallback chain correctness ----------

@settings(max_examples=40, deadline=None)
@given(outcome_seq=st.lists(
    st.sampled_from(["ok", "err", "exc"]),
    min_size=len(IMAGE_MODELS),
    max_size=len(IMAGE_MODELS),
))
def test_image_generation_fallback_chain(outcome_seq):
    chain = list(IMAGE_MODELS)
    outcomes = {m: o for m, o in zip(chain, outcome_seq)}
    parsed, calls = _run_chain(outcomes, chain)

    # 1. Every declared model is attempted exactly once — no model is skipped.
    assert sorted(calls) == sorted(chain), (
        f"chain coverage violated.\n  called   = {sorted(calls)}\n  expected = {sorted(chain)}"
    )
    assert len(calls) == len(chain), f"expected exactly {len(chain)} calls, got {len(calls)}"

    first_ok = _first_success_in_chain(outcomes, chain)

    if first_ok is None:
        # Terminal state: all models failed → model-unavailable.
        assert parsed.get("error") == "model-unavailable", (
            f"expected model-unavailable on all-fail, got {parsed!r}"
        )
        detail = parsed.get("detail", "")
        assert isinstance(detail, str) and len(detail) <= 200, (
            f"detail must be a string of ≤200 chars, got len={len(detail)} type={type(detail)}"
        )
        # Detail must reflect the LAST chain model's failure (deterministic order).
        last_model = chain[-1]
        assert last_model in detail or "exception" in detail.lower(), (
            f"detail should reference last-in-chain failure ({last_model!r}); got {detail!r}"
        )
    else:
        # Success state: response references the first-in-chain successful model.
        assert "error" not in parsed, f"unexpected error on success: {parsed!r}"
        assert parsed.get("model") == first_ok, (
            f"expected winner={first_ok!r} (first ok in chain), got {parsed.get('model')!r}\n"
            f"  outcomes={outcomes}\n  parsed={parsed}"
        )
        path = parsed.get("path", "")
        assert isinstance(path, str) and path.startswith(".generated/"), (
            f"path must start with '.generated/', got {path!r}"
        )
        assert parsed.get("_abs_exists") is True, (
            f"winning model's image file must exist on disk; parsed={parsed!r}"
        )
        # size echoes the requested size (Req 1.3 hand-shake — also covered by Property 3).
        assert parsed.get("size") == "1024x1024", f"size mismatch: {parsed!r}"


def main() -> int:
    print("=== Property 1: 이미지 생성 폴백 체인 정확성 ===")
    print(f"  chain ({len(IMAGE_MODELS)} models): "
          f"{[m.split('.', 1)[1] for m in IMAGE_MODELS]}")
    print(f"  PNG fixture size: {len(_PNG_BYTES):,} bytes")

    test_chain_anchors()
    print("  Req 1.1 anchor order (sd3-5 → core → titan)     OK")

    test_image_generation_fallback_chain()
    print("  fallback chain coverage / first-success / terminal  OK")

    print("All Property 1 cases passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
