"""Property 6: 이미지 편집 폴백 체인 정확성 (Validates: Requirements 2.6, 3.6).

For any sequence of model failures in the edit fallback chain, _tool_edit_image must:
  - try the chain in declared order (deterministic)
  - never skip a model unless a prior one succeeded
  - return the first successful model's result
  - return "model-unavailable" when every model fails
  - try amazon.titan-image-generator-v2:0 before amazon.nova-canvas-v1:0 (Req 2.6/3.6)

The property is tested by patching gw.invoke_model with a per-call outcome list
generated by hypothesis (success / error-response / exception), and inspecting
the recorded call order plus the final JSON response.

Run:
  ai_engine/.venv/bin/python scripts/test_edit_fallback_chain_property.py
"""
from __future__ import annotations

import os
import sys
import json
import asyncio
import base64
import tempfile
from io import BytesIO
from unittest.mock import patch, MagicMock

# Make the ai_engine package importable from the repo root.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from hypothesis import given, settings, strategies as st  # noqa: E402
from PIL import Image  # noqa: E402

from ai_engine.server import (  # noqa: E402
    _tool_edit_image,
    IMAGE_EDIT_MODELS,
    IMAGE_OUTPAINT_MODELS,
)


# ---------- helpers ----------

def _png_bytes(w: int = 4, h: int = 4, color=(255, 255, 255, 255)) -> bytes:
    buf = BytesIO()
    Image.new("RGBA", (w, h), color).save(buf, format="PNG")
    return buf.getvalue()


_PNG_4x4 = _png_bytes(4, 4)
_PNG_4x4_BLACK = _png_bytes(4, 4, color=(0, 0, 0, 255))
_PNG_4x4_B64 = base64.b64encode(_PNG_4x4).decode("ascii")


def _strip_region_prefix(model_id: str) -> str:
    """Strip us./eu./global. prefix attached by _resolve_callable_model_id."""
    for p in ("us.", "eu.", "global."):
        if model_id.startswith(p):
            return model_id[len(p):]
    return model_id


class _ChainSimulator:
    """Records every invoke_model call and replays the supplied outcome list."""

    def __init__(self, outcomes):
        self.outcomes = list(outcomes)
        self.idx = 0
        self.calls: list[str] = []

    async def invoke_model(self, model_id, body, timeout=30):
        self.calls.append(_strip_region_prefix(model_id))
        i = self.idx
        self.idx += 1
        # Defensive: if the chain runs longer than expected the test will fail
        # via the call-count assertion below; fall through with an error here.
        outcome = self.outcomes[i] if i < len(self.outcomes) else "err"
        if outcome == "ok":
            return {"images": [_PNG_4x4_B64]}
        if outcome == "err":
            return {"error": f"simulated error at step {i}"}
        # outcome == "exc"
        raise RuntimeError(f"simulated exception at step {i}")


def _run_chain(mode: str, outcomes):
    """Execute _tool_edit_image with patched gateway and return (parsed_json, calls)."""
    sim = _ChainSimulator(outcomes)
    mock_gw = MagicMock()
    mock_gw.invoke_model = sim.invoke_model

    with tempfile.TemporaryDirectory() as tmp:
        img_path = os.path.join(tmp, "img.png")
        with open(img_path, "wb") as f:
            f.write(_PNG_4x4)

        tool_input = {"mode": mode, "image_path": img_path, "prompt": "test prompt"}
        if mode == "inpaint":
            mask_path = os.path.join(tmp, "mask.png")
            with open(mask_path, "wb") as f:
                f.write(_PNG_4x4_BLACK)
            tool_input["mask_path"] = mask_path
        else:
            tool_input["direction"] = ["right"]
            tool_input["extend_pixels"] = 64

        with patch("ai_engine.server._get_gw", return_value=mock_gw), \
             patch("ai_engine.server._resolve_callable_model_id",
                   side_effect=lambda mid, *a, **k: mid):
            raw = asyncio.run(_tool_edit_image(tool_input, project_path=tmp))

    return json.loads(raw), sim.calls


def _first_success(outcomes):
    for i, o in enumerate(outcomes):
        if o == "ok":
            return i
    return None


def _verify_chain(mode, chain, outcomes, parsed, calls):
    success_idx = _first_success(outcomes)
    expected_calls = chain[: success_idx + 1] if success_idx is not None else list(chain)

    # Deterministic order, no skipping until first success.
    assert calls == expected_calls, (
        f"[{mode}] chain order mismatch.\n  called   = {calls}\n  expected = {expected_calls}"
    )

    if success_idx is None:
        # All models failed → must surface model-unavailable
        assert parsed.get("error") == "model-unavailable", (
            f"[{mode}] expected model-unavailable, got {parsed}"
        )
    else:
        # First success wins; response must reference that exact model id
        assert "error" not in parsed, f"[{mode}] unexpected error on success: {parsed}"
        assert parsed.get("model") == chain[success_idx], (
            f"[{mode}] expected model={chain[success_idx]}, got {parsed.get('model')}"
        )
        assert "path" in parsed and parsed["path"].startswith(".generated/"), (
            f"[{mode}] missing/invalid path: {parsed}"
        )


# ---------- structural invariants of the chain (Req 2.6 / 3.6) ----------

def test_chain_invariants():
    titan = "amazon.titan-image-generator-v2:0"
    nova = "amazon.nova-canvas-v1:0"
    for label, chain in (("inpaint", IMAGE_EDIT_MODELS), ("outpaint", IMAGE_OUTPAINT_MODELS)):
        assert titan in chain, f"[{label}] Titan v2 missing from chain: {chain}"
        assert nova in chain, f"[{label}] Nova Canvas missing from chain: {chain}"
        assert chain.index(titan) < chain.index(nova), (
            f"[{label}] Req 2.6/3.6 violated — Titan must precede Nova Canvas: {chain}"
        )


# ---------- Property 6: inpaint fallback ----------

@settings(max_examples=60, deadline=None)
@given(outcomes=st.lists(
    st.sampled_from(["ok", "err", "exc"]),
    min_size=len(IMAGE_EDIT_MODELS),
    max_size=len(IMAGE_EDIT_MODELS),
))
def test_inpaint_fallback_chain(outcomes):
    parsed, calls = _run_chain("inpaint", outcomes)
    _verify_chain("inpaint", list(IMAGE_EDIT_MODELS), outcomes, parsed, calls)


# ---------- Property 6: outpaint fallback ----------

@settings(max_examples=60, deadline=None)
@given(outcomes=st.lists(
    st.sampled_from(["ok", "err", "exc"]),
    min_size=len(IMAGE_OUTPAINT_MODELS),
    max_size=len(IMAGE_OUTPAINT_MODELS),
))
def test_outpaint_fallback_chain(outcomes):
    parsed, calls = _run_chain("outpaint", outcomes)
    _verify_chain("outpaint", list(IMAGE_OUTPAINT_MODELS), outcomes, parsed, calls)


def main():
    print("=== Property 6: 이미지 편집 폴백 체인 정확성 ===")
    print(f"  inpaint chain  ({len(IMAGE_EDIT_MODELS)} models): "
          f"{[m.split('.', 1)[1] for m in IMAGE_EDIT_MODELS]}")
    print(f"  outpaint chain ({len(IMAGE_OUTPAINT_MODELS)} models): "
          f"{[m.split('.', 1)[1] for m in IMAGE_OUTPAINT_MODELS]}")

    test_chain_invariants()
    print("  invariants (Titan precedes Nova Canvas)         OK")

    test_inpaint_fallback_chain()
    print("  inpaint fallback ordering & terminal states     OK")

    test_outpaint_fallback_chain()
    print("  outpaint fallback ordering & terminal states    OK")

    print("All Property 6 cases passed.")


if __name__ == "__main__":
    main()
